### Priting the iamge and its Dimentions

In [4]:
import cv2

image = cv2.imread("images/my_image2.jpg")

x , y = image.shape[:2]
print("Height = {} , Width = {}.ipynb_checkpoints".format(x,y))

Height = 879 , Width = 772.ipynb_checkpoints


#### Extrcting the RGB values form the Image

In [5]:
(R,G,B) = image[250,250] 
print("R = {} ,G = {},B = {}".format(R,G,B))

B = image[250,250,0]
print("just the values of B = {}".format(B))

R = 85 ,G = 79,B = 96
just the values of B = 85


### Resizing the image to any dimentions:

In [8]:
(r , g, b) = cv2.split(image)
print(r,b,g)

image = cv2.merge((r,g,b))
print(image)

[[175 175 176 ...  75  75  75]
 [175 175 176 ...  75  75  75]
 [176 176 176 ...  75  75  75]
 ...
 [ 62  63  63 ...  46  46  46]
 [ 62  62  62 ...  45  45  45]
 [ 62  62  63 ...  45  45  45]] [[143 143 144 ...  62  62  62]
 [143 143 144 ...  62  62  62]
 [143 143 143 ...  63  63  63]
 ...
 [ 30  31  31 ...  24  24  24]
 [ 30  30  30 ...  23  23  23]
 [ 30  30  31 ...  23  23  23]] [[161 161 162 ...  88  88  88]
 [161 161 162 ...  88  88  88]
 [162 162 162 ...  90  90  90]
 ...
 [ 43  44  44 ...  34  34  34]
 [ 43  43  43 ...  33  33  33]
 [ 43  43  44 ...  33  33  33]]
[[[175 161 143]
  [175 161 143]
  [176 162 144]
  ...
  [ 75  88  62]
  [ 75  88  62]
  [ 75  88  62]]

 [[175 161 143]
  [175 161 143]
  [176 162 144]
  ...
  [ 75  88  62]
  [ 75  88  62]
  [ 75  88  62]]

 [[176 162 143]
  [176 162 143]
  [176 162 143]
  ...
  [ 75  90  63]
  [ 75  90  63]
  [ 75  90  63]]

 ...

 [[ 62  43  30]
  [ 63  44  31]
  [ 63  44  31]
  ...
  [ 46  34  24]
  [ 46  34  24]
  [ 46  34  24]]

 [

In [10]:
import cv2
import numpy as np
 
#importing the opencv module  
import cv2  
# using imread('path') and 1 denotes read as  color image  
img = cv2.imread('images/ikrash1.jpg',1)  
print(img.shape)
img_resized=cv2.resize(img, (780, 540),  
               interpolation = cv2.INTER_NEAREST) 
cv2.imshow("Resized",img_resized)
cv2.waitKey(0)
cv2.destroyAllWindows()


(4032, 3024, 3)


In [12]:
import cv2
import numpy as np
 
#importing the opencv module  
import cv2  
# using imread('path') and 1 denotes read as  color image  
img = cv2.imread('images/ikrash1.jpg',1)  
print(img.shape)
image = cv2.rotate(img, cv2.ROTATE_90_COUNTERCLOCKWISE) 
cv2.imshow("Rotated",image)
cv2.waitKey()
cv2.destroyAllWindows()

(4032, 3024, 3)


In [14]:
import cv2
import numpy as np
 
#importing the opencv module  
import cv2  
# using imread('path') and 1 denotes read as  color image  
img = cv2.imread('images/my_image3.jpeg',1)  
# get image height, width
(h, w) = img.shape[:2]
# calculate the center of the image
center = (w / 2, h / 2)
  
scale = 1.0
  
# Perform the counter clockwise rotation holding at the center
# 45 degrees
M = cv2.getRotationMatrix2D(center, 45, scale)
print(M)
rotated45 = cv2.warpAffine(img, M, (h, w))
  
# 110 degrees
M = cv2.getRotationMatrix2D(center,110, scale)
rotated110 = cv2.warpAffine(img, M, (w, h))
  
# 150 degrees
M = cv2.getRotationMatrix2D(center, 150, scale)
rotated150 = cv2.warpAffine(img, M, (h, w))
  
  
cv2.imshow('Original Image',img)
cv2.waitKey(0) # waits until a key is pressed
cv2.destroyAllWindows() # destroys the window showing image
  
cv2.imshow('Image rotated by 45 degrees',rotated45)
cv2.waitKey(0) # waits until a key is pressed
cv2.destroyAllWindows() # destroys the window showing image
  
cv2.imshow('Image rotated by 110 degrees',rotated110)
cv2.waitKey(0) # waits until a key is pressed
cv2.destroyAllWindows() # destroys the window showing image
  
cv2.imshow('Image rotated by 150 degrees',rotated150)
cv2.waitKey(0) # waits until a key is pressed
cv2.destroyAllWindows() # destroys the window showing image


[[   0.70710678    0.70710678 -153.85908987]
 [  -0.70710678    0.70710678  600.55129855]]


In [20]:
import numpy as np  
import cv2  
img = cv2.imread(r'images/lobab2.jpg', 1)  
cv2.circle(img,(500,500), 400, (255,0,0), 1)  
cv2.imshow('image',img)  
cv2.waitKey(0)  
cv2.destroyAllWindows() 

In [26]:
import numpy as np  
import cv2  
img = cv2.imread(r'images/my_image4.JPG', 1)  
cv2.rectangle(img,(350,55),(550,250),(0,255,0),5)  
cv2.imshow('image',img)  
cv2.waitKey(0)  
cv2.destroyAllWindows()  

In [31]:
import numpy as np  
import cv2  
font = cv2.FONT_HERSHEY_SIMPLEX  
mg = cv2.imread(r'images/ikrash3.jpg', 1)  
cv2.putText(img,'Ikrash khan',(10,500), font, 1,(255,255,255),10)  
#Display the image  
cv2.imshow("image",mg)  
cv2.waitKey(0) 

-1

In [34]:
# OpenCV Python program to detect cars in video frame 
# import libraries of python OpenCV  
import cv2 
   
# capture frames from a video 
cap = cv2.VideoCapture('video.avi') 
   
# Trained XML classifiers describes some features of some object we want to detect 
car_cascade = cv2.CascadeClassifier('cars.xml') 
   
# loop runs if capturing has been initialized. 
while True: 
    # reads frames from a video 
    ret, frames = cap.read() 
       
    # convert to gray scale of each frames 
    gray = cv2.cvtColor(frames, cv2.COLOR_BGR2GRAY) 
       
   
    # Detects cars of different sizes in the input image 
    cars = car_cascade.detectMultiScale(gray, 1.1, 1) 
       
    # To draw a rectangle in each cars 
    for (x,y,w,h) in cars: 
        cv2.rectangle(frames,(x,y),(x+w,y+h),(0,0,255),2) 
   
   # Display frames in a window  
    cv2.imshow('video2', frames) 
       
    # Wait for Esc key to stop 
    if cv2.waitKey(33) == 27: 
        break
   #De-allocate any associated memory usage 
cv2.destroyAllWindows() 

error: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


In [ ]:
import cv2

# Path to video file or device index (0 for the default webcam)
video_source = 'path_to_your_video_file_or_device_index'

# Create a VideoCapture object
cap = cv2.VideoCapture(video_source)

# Check if camera opened successfully
if not cap.isOpened():
    print("Error: Could not open video.")
    exit()

# Load the pre-trained cascade classifier for car detection
car_cascade = cv2.CascadeClassifier('haarcascade_car.xml')

while True:
    # Capture frame-by-frame
    ret, frames = cap.read()
    if not ret:
        print("Error: Failed to read frame.")
        break

    # Convert to gray scale of each frame
    gray = cv2.cvtColor(frames, cv2.COLOR_BGR2GRAY)

    # Detects cars of different sizes in the input image
    cars = car_cascade.detectMultiScale(gray, 1.1, 1)

    # Draw rectangles around the cars
    for (x, y, w, h) in cars:
        cv2.rectangle(frames, (x, y), (x+w, y+h), (0, 0, 255), 2)

    # Display the resulting frame
    cv2.imshow('Frame', frames)

    # Break the loop
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything done, release the video capture object
cap.release()
cv2.destroyAllWindows()


Error: Could not open video.
Error: Failed to read frame.
